export const baseDb = () => ({
  version: 2,
  nextTokenId: 1,
  verifiedWallets: {},
  users: [],
  pendingSessions: [],
  walletChallenges: [],
  properties: [],
  listings: [],
  balances: {},
  approvals: [],
  orders: [],
  leases: [],
  transferEvents: [],
  auditLog: [],
});
